apiVersion: apps/v1
kind: Deployment
metadata:
  name: realm-a
  namespace: realm-a
  labels:
    app: realm-a
    realm: realm-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realm-a
      realm: realm-a
  template:
    metadata:
      labels:
        app: realm-a
        realm: realm-a
        version: v1
    spec:
      containers:
      - name: realm-a
        image: interrealm/realm-a:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: REALM_B_URL
          value: "http://realm-b.realm-b.svc.cluster.local:3002"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: realm-a
  namespace: realm-a
  labels:
    app: realm-a
    realm: realm-a
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: realm-a
    realm: realm-a